language: php
php:
  - 5.5

env:
  - DB=mysql

before_script:
  - composer install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "drop database IF EXISTS danpu;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database danpu;" -uroot; fi

script: phpunit --configuration tests/travis/phpunit.$DB.xml